version: "3.7"
services:
  db:
    container_name: db_app
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
